### PR TITLE
Fix metric descriptor convertion.

### LINKED ISSUE #103: tests: Fix metric-viewdata equivalence tests.
Those tests serialized metrics into JSON and make deep reflect comparison. The proto metric schema changed in the last release, we need to update those tests to match the current schema. 

See https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/102/commits/16d571f14fb5dc5a531fe4cdbe661583b5cf42b0.

### PR DESCRIPTION
**Pull request by songy23**
Fixes #103.

### CODE REVIEW

File: metrics_proto.go [hunk 1]
```diff
@@ -364,26 +371,23 @@ func labelDescriptorsFromProto(defaults map[string]labelValue, protoLabelKeys []
...
-func metricProseFromProto(metric *metricspb.Metric) (name, description, unit string, ok bool) {
-	mname := metric.GetMetricDescriptor().GetName()
-	if mname != "" {
-		name = mname
-		return
-	}
-
+func metricProseFromProto(metric *metricspb.Metric) (name, description, unit string, err error) {
 	md := metric.GetMetricDescriptor()
+	if md == nil {
```
Comment (songy23) [inline metrics_proto.go]: https://github.com/census-instrumentation/opencensus-proto/pull/184 reverts the optimization on sending metric name instead of metric descriptor. Thus metric descriptors should always be non-nil.
