### PR TITLE
fix goimports error in test.pb.go file.

### LINKED ISSUE #247: make travis-ci fails with goimports error in test.pb.go
git:(master) make travis-ci
Fmt finished successfully
Lint finished successfully
Vet finished successfully
Embedmd finished successfully
goimports FAILED => fix the following goimports errors:

diff -u internal/testpb/test.pb.go.orig internal/testpb/test.pb.go
--- internal/testpb/test.pb.go.orig	2020-01-17 10:58:26.000000000 -0800
+++ internal/testpb/test.pb.go	2020-01-17 10:58:26.000000000 -0800
@@ -13,12 +13,15 @@
 */
 package testpb

-import proto "github.com/golang/protobuf/proto"
-import fmt "fmt"
-import math "math"
-
 import (
+	fmt "fmt"
+
+	proto "github.com/golang/protobuf/proto"
+
+	math "math"
+
 	context "golang.org/x/net/context"
+
 	grpc "google.golang.org/grpc"
 )

make: *** [goimports] Error 1

### PR DESCRIPTION
**Pull request by rghetia**
fixes #247 

- modified generate.sh to run goimports on generated file.
- added additional line before generated comment to fix golint error in test.pb.go

### CODE REVIEW

File: internal/testpb/generate.sh [hunk 1]
```diff
@@ -2,6 +2,8 @@
 # generate .pb.go file from .proto file.
 set -e
 protoc --go_out=plugins=grpc:. test.proto
-echo '//go:generate ./generate.sh
+echo '
+//go:generate ./generate.sh
 ' >> test.pb.go
+goimports -w test.pb.go
```
Comment (songy23) [inline internal/testpb/generate.sh]: Is it possible to include other go files too (if added later)?

Comment (rghetia) [reply internal/testpb/generate.sh]: It is possible to make it generic but i would like to defer that until we have another proto file.

Comment (songy23) [reply internal/testpb/generate.sh]: SG
